platform :ios, '7.0'

pod 'RNCryptor',                 '~> 2.1'
pod 'AFNetworking', '~> 2.0'  
pod 'ObjectiveSugar', '~> 0.5'
pod 'Bolts'
pod 'Appirater'
pod 'EDQueue'
pod 'OHHTTPStubs'
pod 'PNChart'
pod 'SDWebImage'
pod 'SSKeychain'
pod 'SVPullToRefresh'
pod 'TMCache'
pod 'UIColor+FlatColors'
pod 'libPhoneNumber-iOS',        '~> 0.7.3'
pod 'Realm'
pod 'JSONModel'
pod 'GoogleProtobuf'
pod 'TouchJSON'
pod 'ZipArchive'