platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.0'
pod 'AFNetworkActivityLogger', '~> 2.0'
#pod 'ObjectiveSugar', '~> 0.5'
#pod 'Appirater'
#pod 'PNChart', '0.8'
pod 'SDWebImage'
pod 'SSKeychain'
pod 'TMCache'
pod 'UIColor+FlatColors'
#pod 'libPhoneNumber-iOS',        '~> 0.7.3'
pod 'Realm'
pod 'GoogleProtobuf', '2.5.0'
#pod 'ZipArchive'
pod 'CocoaAsyncSocket'
pod 'HTKDynamicResizingCell'
#pod 'UIImage+ImageCompress'
#pod 'LMMediaPlayer'
pod 'ArrayUtils'
pod 'QBImagePickerController'
#pod 'FMDB/SQLCipher'
pod 'NSDate+TimeAgo', '~> 1.0'