platform :ios, '8.0'

pod 'RNCryptor',                 '~> 2.1'
pod 'AFNetworking', '~> 2.0'
pod 'AFNetworkActivityLogger', '~> 2.0'
pod 'ObjectiveSugar', '~> 0.5'
pod 'Bolts'
pod 'Appirater'
pod 'EDQueue'
pod 'OHHTTPStubs'
pod 'PNChart', '0.8'
pod 'SDWebImage'
pod 'SSKeychain'
pod 'SVPullToRefresh'
pod 'TMCache'
pod 'UIColor+FlatColors'
pod 'libPhoneNumber-iOS',        '~> 0.7.3'
pod 'Realm'
pod 'GoogleProtobuf', '2.5.0'
pod 'TouchJSON'
pod 'ZipArchive'
pod 'CocoaAsyncSocket'
pod 'DOUAudioStreamer'
pod 'ReactiveCocoa'
pod 'HTKDynamicResizingCell'
pod 'UIImage+ImageCompress'
pod 'LMMediaPlayer'
pod 'AFSoundManager'
pod 'Robocop'
pod 'JSQSystemSoundPlayer'
pod 'ArrayUtils'
pod 'QBImagePickerController'